In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available")

CUDA is not available


## Creating a Tensor

In [7]:
a= torch.empty(2,3)
#it creates space in memory and shows already existing values in this space
print(a)

tensor([[1.6450e-33, 0.0000e+00, 1.6449e-33],
        [0.0000e+00, 2.7606e-43, 2.8026e-43]])


In [6]:
type(a)

torch.Tensor

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.rand(2,3)

tensor([[0.1164, 0.4851, 0.7005],
        [0.4922, 0.9660, 0.8222]])

In [12]:
torch.manual_seed(100)
 # used in case if someone want's to use this notebook and wants same random values
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# creating a manual tensor
torch.tensor([[1,2,3], [4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# can also create tensors using

#arange
print("using arange ->", torch.arange(0,10))

#using linspace
print("using linspace ->", torch.linspace(0,10,10))

#using eye
print("using eye=> ",torch.eye(5) ) #creating identity matrix

#using full
print("using full->", torch.full((3,3),5)) #creates a matrix with given value

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye=>  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [18]:
#will create same shape tensor of given tensor but with different values
torch.empty_like(x)

tensor([[              0,       152416224,       125161296],
        [132686068016400,               0,               0]])

In [19]:
#will create same shape tensor of given tensor but with zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
#will create same shape tensor of given tensor but with ones
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
torch.rand_like(x)
# will create error because of data type =

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [27]:
# fixed error
torch.rand_like(x, dtype= torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [22]:
# find data type
x.dtype

torch.int64

In [24]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
# changing data type usign to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

### 1. Scalar Operations

In [28]:
x = torch.rand(2,2)

In [29]:
# addition
x+2
# subtraction
x-2
# multiplication
x*3
# division
x/3
# int division
(x*100)//3

#mod
(((x*100))//3) %2

# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

## Element wise operation

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [32]:
# add
a + b
# sub
a-b
# mul
a*b
# divide
a/b
# power
a**b
#mod
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [33]:
# abs
torch.abs(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [42]:
#negative
c = torch.rand(2,3)
torch.neg(c)
#round
d = torch.rand(2,3)
torch.round(d)
# #ceil
# torch.ceil(d)
# #floor
# torch.floor(d)
torch.clamp(d,min=0.5, max=1)

tensor([[0.5000, 0.5000, 0.5000],
        [0.9753, 0.7582, 0.6688]])

## Reduction Operator

In [46]:
e = torch.randint(size=(2,3), low=0, high = 10, dtype = torch.float32)
e

tensor([[4., 4., 6.],
        [2., 1., 0.]])

In [45]:
#sum
print(torch.sum(e))
#sum along columns)
print(torch.sum(e, dim=0))
#sum along rows
print(torch.sum(e, dim=1))

tensor(27)
tensor([14,  9,  4])
tensor([18,  9])


In [51]:
#mean
print(torch.mean(e))
#median
print(torch.median(e))
#max and min
print(torch.max(e))
print(torch.min(e))
#std
print(torch.std(e))
#variance
print(torch.var(e))
#product
print(torch.prod(e))
#cummulative sum
print(torch.cumsum(e,dim=0))
#cummulative product
print(torch.cumprod(e,dim=0))
print(torch.argmin(e))
print(torch.argmax(e))

tensor(2.8333)
tensor(2.)
tensor(6.)
tensor(0.)
tensor(2.2286)
tensor(4.9667)
tensor(0.)
tensor([[4., 4., 6.],
        [6., 5., 6.]])
tensor([[4., 4., 6.],
        [8., 4., 0.]])
tensor(5)
tensor(2)


## Matrix Operations

In [52]:
f = torch.randint(size=(2,3), low=0, high =10)
g = torch.randint(size=(3,2), low=0, high =10)


tensor([[5, 1, 0],
        [0, 2, 2]])
tensor([[3, 7],
        [1, 5],
        [0, 2]])


In [65]:
# matrix multiplication
l = torch.matmul(f,g)


In [54]:
vector_1 = torch.tensor([1,2])
vector_2 = torch.tensor([3,4])

torch.dot(vector_1,vector_2)

tensor(11)

In [56]:
# transpose
torch.transpose(f,0,1)

tensor([[5, 0],
        [1, 2],
        [0, 2]])

In [68]:

h = torch.randint(size=(4,4), low = 0, high =10, dtype=torch.float32)


tensor([[6., 5., 4., 1.],
        [1., 3., 9., 4.],
        [7., 6., 6., 5.],
        [1., 4., 2., 6.]])

In [70]:
#determinat
print(torch.det(h))
print(torch.inverse(h))

tensor(501.0001)
tensor([[-0.2275, -0.1078,  0.3832, -0.2096],
        [ 0.5489,  0.0319, -0.5210,  0.3214],
        [-0.0140,  0.1337,  0.0060, -0.0918],
        [-0.3234, -0.0479,  0.2814,  0.0180]])


In [76]:
#greater than
vector_1>vector_2
#less than
vector_1<vector_2
#not equal to
vector_1!=vector_2


tensor([True, True])

In [81]:
#exp
torch.exp(vector_1)
#log
torch.log(vector_1)
#sqrt
torch.sqrt(vector_1)
#sigmoid
torch.sigmoid(vector_1)
#softmax
torch.softmax(h, dim=0)
#relu
torch.relu(vector_1)
#tanh
torch.tanh(vector_1)
#clamp
torch.clamp(vector_1,min=0,max=1)

tensor([1, 1])

## Inplace Operations

In [82]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.5301, 0.6401, 0.7954],
        [0.3066, 0.2397, 0.1156]])
tensor([[0.4839, 0.3944, 0.0801],
        [0.7782, 0.6686, 0.2312]])


In [84]:
m.add_(n) # will store result in m

tensor([[1.0141, 1.0345, 0.8755],
        [1.0849, 0.9082, 0.3468]])

In [85]:
print(m)

tensor([[1.0141, 1.0345, 0.8755],
        [1.0849, 0.9082, 0.3468]])


In [86]:
n

tensor([[0.4839, 0.3944, 0.0801],
        [0.7782, 0.6686, 0.2312]])

In [87]:
torch.relu(m)

tensor([[1.0141, 1.0345, 0.8755],
        [1.0849, 0.9082, 0.3468]])

In [88]:
torch.relu(n)

tensor([[0.4839, 0.3944, 0.0801],
        [0.7782, 0.6686, 0.2312]])

## Copying a tensor

In [92]:
b = a.clone()

In [95]:
print(a)
print(b)

tensor([[0.1164, 0.1921],
        [0.2380, 0.1643]])
tensor([[0.1164, 0.1921],
        [0.2380, 0.1643]])


In [96]:
torch.cuda.is_available()

False

## Reshaping Tensors

In [101]:
# reshape
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [103]:
#flattening
a.flatten

<function Tensor.flatten>

In [104]:
b = torch.rand(2,3,4)
b

tensor([[[0.1406, 0.2950, 0.3264, 0.4708],
         [0.3978, 0.7055, 0.9162, 0.8060],
         [0.7267, 0.8054, 0.1696, 0.2023]],

        [[0.9194, 0.0151, 0.0324, 0.9538],
         [0.5564, 0.7567, 0.1573, 0.3969],
         [0.2381, 0.1268, 0.4460, 0.0370]]])

In [106]:
#permute
b = torch.rand(2,3,4)
b

tensor([[[0.6442, 0.8108, 0.2550, 0.8608],
         [0.8250, 0.2236, 0.0772, 0.4818],
         [0.0776, 0.0531, 0.2610, 0.1068]],

        [[0.3011, 0.4587, 0.5222, 0.0683],
         [0.9118, 0.8286, 0.1635, 0.1775],
         [0.7163, 0.9355, 0.1430, 0.3933]]])

In [109]:
#permuting it
b.permute(2,0,1)
# will change the seqeunce of dimensions

tensor([[[0.6442, 0.8250, 0.0776],
         [0.3011, 0.9118, 0.7163]],

        [[0.8108, 0.2236, 0.0531],
         [0.4587, 0.8286, 0.9355]],

        [[0.2550, 0.0772, 0.2610],
         [0.5222, 0.1635, 0.1430]],

        [[0.8608, 0.4818, 0.1068],
         [0.0683, 0.1775, 0.3933]]])

In [112]:
#unsqueeze
#will use to add a new dimension at given index
c= torch.rand(226,226,3)
print(c.unsqueeze(1).shape)
print(c.unsqueeze(0).shape )


torch.Size([226, 1, 226, 3])
torch.Size([1, 226, 226, 3])


In [114]:
#squeez
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [115]:
import numpy as np

In [116]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [118]:
b = a.numpy()
b

array([1, 2, 3])

In [119]:
type(b)

numpy.ndarray

In [122]:
c = np.array([1,2,3])

In [123]:
torch.from_numpy(c)

tensor([1, 2, 3])